name    'pdxcat-auditd'
version '0.0.1'
source 'https://github.com/pdxcat/puppet-module-auditd'
author 'Computer Action Team'
license 'Apache License 2.0'
summary 'Auditd Module for Puppet'
description 'Auditd Module for Puppet'
project_page 'https://github.com/pdxcat/puppet-module-auditd'
